#!/bin/bash
#repo changer v 1.2
#coded by D_baj

#color                                                                
o='\033[0m'; r='\033[1;31m'; b='\033[1;36m'; bx='\033[2;7;36m'; w='\033[1;37m'; y='\033[1;33m'; g='\033[1;32m'
#modul
N=$w'['$r'~'$w'] '
P=$w'['$r'?'$w'] '                                
P2=$w'['$r'*'$w'] '
W=$w'['$r'!'$w'] '
I=$w'['$r'+'$w'] '
D=$w'['$g'✓'$w'] '
ER1=$r'pilihan yang anda pilih salah !'
num0=$g'['$w'00'$g']'$w
num1=$g'['$w'01'$g']'$w
num2=$g'['$w'02'$g']'$w
num3=$g'['$w'03'$g']'$w
num4=$g'['$w'04'$g']'$w                               
num6=$g'['$w'06'$g']'$w
num7=$g'['$w'07'$g']'$w
num8=$g'['$w'08'$g']'$w
SOURCE_DIR="$PREFIX/etc/apt/sources.list.d"
banner() {
clear
echo -e $r'          __________'
echo -e $r'          \______   \ '$g'____ ______   ____ '
echo -e $r'           |       _/'$g'/ __ \\_ ___ \ /  _ \'
echo -e $r'           |    |   \ '$g' ___/|  |_> >  <_> )'
echo -e $r'           |____|_  /'$g'\___  >   __/ \____/'
echo -e $r'                  \/'$g'     \/|__|'$o'          '$bx'v 1.2'$o''
echo -e $y'.:.:.:.:.:. repo changer coded by D_baj .:.:.:.:.:.'
}
opsi() {
  banner
  echo ""
  echo -e "${num1} Default (${g}recomennded${w})
${num2} Grimler
${num3} Kcubeterm
${num4} A1batross
${num0} Exit"
  read -p $'\033[1;37m[\033[1;31m?\033[1;37m] Silahkan pilih miror: ' menu
  if [[ $menu = "01" || $menu = "1" ]]; then
    MIRROR=${pwd}".repo_list/default"
    selected="Default"
    run
  elif [[ $menu = "02" || $menu = "2" ]]; then
    MIRROR=${pwd}".repo_list/grimler"
    selected="Grimler"
    run
  elif [[ $menu = "03" || $menu = "3" ]]; then
    MIRROR=${pwd}".repo_list/kcubeterm"
    selected="Kcubeterm"
    run
  elif [[ $menu = "04" || $menu = "4" ]]; then
    MIRROR=${pwd}".repo_list/a1batross"
    selected="A1batross"
    run
  elif [[ $menu = "00" || $menu = "0" ]]; then
    close
  else
    $ER1
    opsi
  fi

}
close() {
  banner
  echo ""
  echo -e "${g}    Terimakasih sudah menggunakan tools ini : )"
  exit
}
run() {
  banner
  echo ""
  echo -e $g"MIRROR SELECTED: ${selected}"
  echo ""
  echo -e $b
  pwd
  echo ""
  echo ""
  echo -e "${P2}Copy tulisan yg berwarna Biru"
  read -p $'\033[1;37m[\033[1;31m*\033[1;37m] Paste/Tempel di sini : ' pwd
  read -p $'\033[1;37m[\033[1;31m?\033[1;37m] Do you want to continue? (y/n): ' con
  if [[ $con = "y" || $con = "Y" ]]; then
    echo -e "${I}please wait ..."
    sleep 2s
    cd $SOURCE_DIR
    rm -rf *
    echo -e "${I}Installing ..."
    sleep 2s
    cd $pwd
    cd $MIRROR
    cp * $SOURCE_DIR
    echo -e "${I}Testing ..."
    pkg update && pkg upgrade
    echo -e "${D}DONE"
    read -p $'please press enter to exit: ' exit
    close

  elif [[ $con = "n" || $con = "N" ]]; then
    close
  fi
}
opsi


